#%RAML 1.0 DataType

properties:
  finish:
    example: 0
    type: number
    format: int
  player:
    example: playerName
    type: string
  wins:
    example: 0
    type: number
    format: int
  losses:
    example: 0
    type: number
    format: int
  byes:
    example: 0
    type: number
    format: int
  arch:
    example: archName
    type: string
  subarch:
    example: subarchName
    type: string
  deck:
    example: deckName
    type: string
  eventId:
    example: 2023-01-01-EventType-1
    type: string