#%RAML 1.0
title: Vintage Metagame API
mediaType: application/json
version: 1.0.0

types:
  Error: !include types/Error.raml
  Event: !include types/Event.raml
  Finish: !include types/Finish.raml

traits:
  commonErrorResponses:
    responses:
      400:
        body: Error
      500:
        body: Error

/events:
  is:
    - commonErrorResponses
  get:
    responses:
      200:
        body: Event[]
      400:
        body: Error
  post:
    body: Event
    responses:
      201:
        body: Event
      409:
        body: Error
  /{eventId}:
    is:
      - commonErrorResponses
    uriParameters:
      eventId:
        example: 2023-01-01-Event-1
        type: string
    get:
      responses:
        200:
          body: Event
        404:
          body: Error
    put:
      body: Event
      responses:
        200:
          body: Event
        404:
          body: Error
    delete:
      responses:
        204:
        404:
          body: Error
    /finishes:
      is:
        - commonErrorResponses
      get:
        responses:
          200:
            body: Finish[]
          404:
            body: Error
      post:
        body: Finish
        responses:
          201:
            body: Finish
          409:
            body: Error
      /{finishRank}:
        is:
          - commonErrorResponses
        uriParameters:
          finishRank:
            example: 1
            type: number
            format: int
        get:
          responses:
            200:
              body: Finish
            404:
              body: Error
        put:
          body: Finish
          responses:
            200:
              body: Finish
            404:
              body: Error
        delete:
          responses:
            204:
            404:
              body: Error